---         
apiVersion: v1
kind: Service
metadata:
  name: {{ template "amundsen.name" . }}-{{ .Values.frontEnd.serviceName }}
  labels:
    app.kubernetes.io/component: {{ .Values.frontEnd.serviceName }}
    app.kubernetes.io/name: {{ include "amundsen.name" . }}
    helm.sh/chart: {{ include "amundsen.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

{{- with .Values.frontEnd.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end}}   
spec:
  type: {{ .Values.frontEnd.serviceType }}
  selector:
    app.kubernetes.io/name: {{ include "amundsen.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: {{ .Chart.Name }}-{{ .Values.frontEnd.serviceName }}-http
      port: 5000
      targetPort: frontendport