---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "amundsen.fullname" . }}-{{ .Values.frontEnd.serviceName }}
  labels:
    app.kubernetes.io/component: {{ .Values.frontEnd.serviceName }}
    app.kubernetes.io/name: {{ include "amundsen.name" . }}
    helm.sh/chart: {{ include "amundsen.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.frontEnd.serviceName }}
      app.kubernetes.io/name: {{ include "amundsen.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: {{ default 1 .Values.frontEnd.replicas }}
  template:
    metadata:
      {{- with default .Values.podAnnotations .Values.frontEnd.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: {{ .Values.frontEnd.serviceName }}
        app.kubernetes.io/name: {{ include "amundsen.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with default .Values.nodeSelector .Values.frontEnd.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with default .Values.affinity .Values.frontEnd.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with default .Values.tolerations .Values.frontEnd.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.frontEnd.oidcEnabled }}
        - name: oidc-config
          secret:
            secretName: {{ include "amundsen.fullname" . }}-oidc-config
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-{{ .Values.frontEnd.serviceName }}
        image: {{ .Values.frontEnd.image }}:{{ .Values.frontEnd.imageTag }}
        imagePullPolicy: Always
        ports:
          - name: frontendport
            containerPort: 5000
        env:
          - name: FRONTEND_BASE
            value: {{ .Values.frontEnd.baseUrl }}
          - name: SEARCHSERVICE_BASE
            value: http://{{ include "amundsen.fullname" . }}-{{ .Values.search.serviceName }}.{{ .Release.Namespace }}.svc.cluster.local:5001
          - name: METADATASERVICE_BASE
            value: http://{{ include "amundsen.fullname" . }}-{{ .Values.metadata.serviceName }}.{{ .Release.Namespace }}.svc.cluster.local:5002
          - name: LONG_RANDOM_STRING
            value: {{ quote .Values.LONG_RANDOM_STRING }}
        {{- if .Values.frontEnd.oidcEnabled }}
          - name: FRONTEND_SVC_CONFIG_MODULE_CLASS
            value: amundsen_application.oidc_config.OidcConfig
          - name: FLASK_OIDC_WHITELISTED_ENDPOINTS
            value: status,healthcheck,health
          - name: FLASK_OIDC_SQLALCHEMY_DATABASE_URI
            value: sqlite:///sessions.db
          - name: APP_WRAPPER
            value: flaskoidc
          - name: APP_WRAPPER_CLASS
            value: FlaskOIDC
          - name: FLASK_OIDC_CLIENT_SECRETS
            value: /etc/client_secrets.json
          - name: FLASK_OIDC_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "amundsen.fullname" . }}-oidc-config
                key: OIDC_CLIENT_SECRET
        {{- end }}
        {{- range $key, $value :=  .Values.frontEnd.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
        {{- end }}
        {{- if or .Values.frontEnd.extraEnvVarsCM .Values.frontEnd.extraEnvVarsSecret }}
        envFrom:
          {{- if .Values.frontEnd.extraEnvVarsCM }}
          - configMapRef:
              name: {{ include "amundsen.tplValue" ( dict "value" .Values.frontEnd.extraEnvVarsCM "context" $ ) }}
          {{- end }}
          {{- if .Values.frontEnd.extraEnvVarsSecret }}
          - secretRef:
              name: {{ include "amundsen.tplValue" ( dict "value" .Values.frontEnd.extraEnvVarsSecret "context" $ ) }}
          {{- end }}
        {{- end }}

        livenessProbe:
          httpGet:
            path: "/healthcheck"
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        {{- if .Values.frontEnd.oidcEnabled }}
          - name: oidc-config
            mountPath: /etc/client_secrets.json
            subPath: client_secrets.json
        {{- end }}
        {{- with .Values.metadata.resources }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end }}