apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "amundsen.fullname" . }}-{{ .Values.search.serviceName }}
  labels:
    app.kubernetes.io/component: {{ .Values.search.serviceName }}
    app.kubernetes.io/name: {{ include "amundsen.name" . }}
    helm.sh/chart: {{ include "amundsen.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.search.serviceName }}
      app.kubernetes.io/name: {{ include "amundsen.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: {{ default 1 .Values.search.replicas }}
  template:
    metadata:
      {{- with default .Values.podAnnotations .Values.search.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: {{ .Values.search.serviceName }}
        app.kubernetes.io/name: {{ include "amundsen.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with default .Values.nodeSelector .Values.search.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with default .Values.affinity .Values.search.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with default .Values.tolerations .Values.search.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-{{ .Values.search.serviceName }}
        image: {{ .Values.search.image }}:{{ .Values.search.imageTag }}
        ports:
        - name: searchport
          containerPort: 5001
        env:
        - name: PROXY_ENDPOINT
          value: {{ if .Values.search.elasticsearchEndpoint }}{{ .Values.search.elasticsearchEndpoint }}{{ else }}{{ .Release.Name }}-elasticsearch-client.{{ .Release.Namespace }}.svc.cluster.local{{ end }}
        livenessProbe:
          httpGet:
            path: "/healthcheck"
            port: 5001
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        {{- with .Values.search.resources }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end }}