apiVersion: v1
kind: Service
metadata:
  name: {{ include "amundsen.fullname" . }}-{{ .Values.search.serviceName }}
  labels:
    app.kubernetes.io/component: {{ .Values.search.serviceName }}
    app.kubernetes.io/name: {{ include "amundsen.name" . }}
    helm.sh/chart: {{ include "amundsen.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.search.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end}}   
spec:
  type: {{ .Values.search.serviceType }}
  selector:
    app.kubernetes.io/component: {{ .Values.search.serviceName }}
    app.kubernetes.io/name: {{ include "amundsen.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: {{ .Chart.Name }}-{{ .Values.search.serviceName }}-http
      port: 5001
      targetPort: searchport