{{- if .Values.frontEnd.createOidcSecret }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "amundsen.fullname" . }}-oidc-config
    namespace: {{ .Release.Namespace }}
stringData:
  OIDC_CLIENT_SECRET: {{ .Values.frontEnd.env.OIDC_CLIENT_SECRET }}
  client_secrets.json: |-
    {
      "web": {
        "client_id": "{{ .Values.frontEnd.env.OIDC_CLIENT_ID }}",
        "client_secret": "{{ .Values.frontEnd.env.OIDC_CLIENT_SECRET }}",
        "auth_uri": "{{ .Values.frontEnd.env.OIDC_ORG_URL }}/oauth2/{{ .Values.frontEnd.env.OIDC_AUTH_SERVER_ID }}/v1/authorize",
        "token_uri": "{{ .Values.frontEnd.env.OIDC_ORG_URL }}/oauth2/{{ .Values.frontEnd.env.OIDC_AUTH_SERVER_ID }}/v1/token",
        "issuer": "{{ .Values.frontEnd.env.OIDC_ORG_URL }}/oauth2/{{ .Values.frontEnd.env.OIDC_AUTH_SERVER_ID }}",
        "userinfo_uri": "{{ .Values.frontEnd.env.OIDC_ORG_URL }}/oauth2/{{ .Values.frontEnd.env.OIDC_AUTH_SERVER_ID }}/v1/userinfo",
        "redirect_uris": [
          "http://localhost/oidc_callback"
        ],
        "token_introspection_uri": "{{ .Values.frontEnd.env.OIDC_ORG_URL }}/oauth2/{{ .Values.frontEnd.env.OIDC_AUTH_SERVER_ID }}/v1/introspect"
      }
    }
{{- end }}