dependencies:
 - name: neo4j
   version: 1.2.2
   repository: https://kubernetes-charts.storage.googleapis.com/
   condition: neo4j.enabled
  - name: elasticsearch
    version: 1.32.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: elasticsearch.enabled