dependencies:
  # - name: neo4j-community
  #   version: 1.1.0
  #   repository: https://equinor.github.io/helm-charts/charts/
  #   condition: neo4j.enabled
  - name: elasticsearch
    version: 1.32.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: elasticsearch.enabled