name: Helm Template Validation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Helm Templates Validation
      uses: igabaydulin/helm-check-action@0.1.4
